
export const ANNOUNCEMENT_ITEM_REQUEST = 'ANNOUNCEMENT_ITEM_REQUEST';
export const ANNOUNCEMENT_ITEM_SUCCESS = 'ANNOUNCEMENT_ITEM_SUCCESS';
export const ANNOUNCEMENT_ITEM_FAIL = 'ANNOUNCEMENT_ITEM_FAIL';

export const ANNOUNCEMENT_CREATE_FORM_REQUEST = 'ANNOUNCEMENT_CREATE_FORM_REQUEST';
export const ANNOUNCEMENT_CREATE_FORM_SUCCESS = 'ANNOUNCEMENT_CREATE_FORM_SUCCESS';
export const ANNOUNCEMENT_CREATE_FORM_FAIL = 'ANNOUNCEMENT_CREATE_FORM_FAIL';

export const ANNOUNCEMENT_CREATE_ITEM_SUCCESS = 'ANNOUNCEMENT_CREATE_ITEM_SUCCESS';
export const ANNOUNCEMENT_CREATE_ITEM_FAIL = 'ANNOUNCEMENT_CREATE_ITEM_FAIL';
export const ANNOUNCEMENT_CREATE_ITEM_RESET = 'ANNOUNCEMENT_CREATE_ITEM_RESET';

export const ANNOUNCEMENT_CREATE_ITEM = 'ANNOUNCEMENT_CREATE_ITEM';
export const ANNOUNCEMENT_DELETE_ITEM = 'ANNOUNCEMENT_DELETE_ITEM';

export const ANNOUNCEMENT_DETAILS_REQUEST = 'ANNOUNCEMENT_DETAILS_REQUEST';
export const ANNOUNCEMENT_DETAILS_SUCCESS = 'ANNOUNCEMENT_DETAILS_SUCCESS';
export const ANNOUNCEMENT_DETAILS_FAIL = 'ANNOUNCEMENT_DETAILS_FAIL';
